<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="10" ignored="0" total="12" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="220175" started-at="2019-04-18T11:08:36Z" finished-at="2019-04-18T11:12:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="220175" started-at="2019-04-18T11:08:36Z" finished-at="2019-04-18T11:12:16Z">
      <class name="com.createinternaluser.CreateInternalUserWithValidData">
        <test-method status="PASS" signature="init()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="init" is-config="true" duration-ms="276" started-at="2019-04-18T16:38:36Z" finished-at="2019-04-18T16:38:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="initGlobalVar()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="initGlobalVar" is-config="true" duration-ms="2" started-at="2019-04-18T16:38:36Z" finished-at="2019-04-18T16:38:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initGlobalVar -->
        <test-method status="PASS" signature="initApplication(java.lang.String)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="initApplication" is-config="true" duration-ms="4365" started-at="2019-04-18T16:38:36Z" finished-at="2019-04-18T16:38:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initApplication -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="2402" started-at="2019-04-18T16:38:40Z" finished-at="2019-04-18T16:38:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="PASS" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="17852" started-at="2019-04-18T16:38:43Z" finished-at="2019-04-18T16:39:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="3" started-at="2019-04-18T16:39:01Z" finished-at="2019-04-18T16:39:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=SUCCESS method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="410" started-at="2019-04-18T16:39:01Z" finished-at="2019-04-18T16:39:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="PASS" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="17069" started-at="2019-04-18T16:39:01Z" finished-at="2019-04-18T16:39:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="2" started-at="2019-04-18T16:39:18Z" finished-at="2019-04-18T16:39:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=SUCCESS method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="446" started-at="2019-04-18T16:39:18Z" finished-at="2019-04-18T16:39:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="17102" started-at="2019-04-18T16:39:18Z" finished-at="2019-04-18T16:39:36Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="383" started-at="2019-04-18T16:39:36Z" finished-at="2019-04-18T16:39:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="392" started-at="2019-04-18T16:39:36Z" finished-at="2019-04-18T16:39:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="16935" started-at="2019-04-18T16:39:36Z" finished-at="2019-04-18T16:39:53Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="457" started-at="2019-04-18T16:39:53Z" finished-at="2019-04-18T16:39:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="425" started-at="2019-04-18T16:39:54Z" finished-at="2019-04-18T16:39:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="16914" started-at="2019-04-18T16:39:54Z" finished-at="2019-04-18T16:40:11Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="344" started-at="2019-04-18T16:40:11Z" finished-at="2019-04-18T16:40:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="445" started-at="2019-04-18T16:40:11Z" finished-at="2019-04-18T16:40:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="17033" started-at="2019-04-18T16:40:12Z" finished-at="2019-04-18T16:40:29Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="354" started-at="2019-04-18T16:40:29Z" finished-at="2019-04-18T16:40:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="404" started-at="2019-04-18T16:40:29Z" finished-at="2019-04-18T16:40:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="17204" started-at="2019-04-18T16:40:30Z" finished-at="2019-04-18T16:40:47Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="347" started-at="2019-04-18T16:40:47Z" finished-at="2019-04-18T16:40:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="400" started-at="2019-04-18T16:40:47Z" finished-at="2019-04-18T16:40:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="16960" started-at="2019-04-18T16:40:48Z" finished-at="2019-04-18T16:41:05Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="354" started-at="2019-04-18T16:41:05Z" finished-at="2019-04-18T16:41:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="424" started-at="2019-04-18T16:41:05Z" finished-at="2019-04-18T16:41:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="16951" started-at="2019-04-18T16:41:05Z" finished-at="2019-04-18T16:41:22Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="357" started-at="2019-04-18T16:41:22Z" finished-at="2019-04-18T16:41:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="409" started-at="2019-04-18T16:41:23Z" finished-at="2019-04-18T16:41:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="17018" started-at="2019-04-18T16:41:23Z" finished-at="2019-04-18T16:41:40Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="350" started-at="2019-04-18T16:41:40Z" finished-at="2019-04-18T16:41:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="386" started-at="2019-04-18T16:41:40Z" finished-at="2019-04-18T16:41:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="17015" started-at="2019-04-18T16:41:41Z" finished-at="2019-04-18T16:41:58Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="338" started-at="2019-04-18T16:41:58Z" finished-at="2019-04-18T16:41:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="preCondtion(java.lang.reflect.Method)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="preCondtion" is-config="true" duration-ms="384" started-at="2019-04-18T16:41:58Z" finished-at="2019-04-18T16:41:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData() throws java.lang.InterruptedException,java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondtion -->
        <test-method status="FAIL" signature="testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="testCreateInternalUserWithValidData" duration-ms="16963" started-at="2019-04-18T16:41:59Z" finished-at="2019-04-18T16:42:16Z">
          <exception class="org.postgresql.util.PSQLException">
            <message>
              <![CDATA[ResultSet not positioned properly, perhaps you need to call next.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:2467)
	at com.createinternaluser.CreateInternalUserWithValidData.testCreateInternalUserWithValidData(CreateInternalUserWithValidData.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.postgresql.util.PSQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateInternalUserWithValidData -->
        <test-method status="PASS" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="postCondition" is-config="true" duration-ms="341" started-at="2019-04-18T16:42:16Z" finished-at="2019-04-18T16:42:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateInternalUserWithValidData status=FAILURE method=CreateInternalUserWithValidData.testCreateInternalUserWithValidData()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="closeApplication" is-config="true" duration-ms="175" started-at="2019-04-18T16:42:16Z" finished-at="2019-04-18T16:42:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method status="PASS" signature="publishReport()[pri:0, instance:com.createinternaluser.CreateInternalUserWithValidData@610694f1]" name="publishReport" is-config="true" duration-ms="523" started-at="2019-04-18T16:42:16Z" finished-at="2019-04-18T16:42:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- publishReport -->
      </class> <!-- com.createinternaluser.CreateInternalUserWithValidData -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
